### ISSUE TITLE
Task: publiceer datasets metadata in beng-lod-server

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/opendatalab#13]
## TODO
- [x]  importeer de spreadsheet 
[Spreadsheet Maarten & Dimitra](https://docs.google.com/spreadsheets/d/14KEFxuNfM9yezKssyUHrGuhL6sRC6ATvtPcrghKNh8s/edit?usp=sharing)
- [x] publiceer de datasets als RDF op de beng-lod-server (conform [NDE requirements](https://github.com/netwerk-digitaal-erfgoed/project-organisations-datasets/tree/master/publication-model)) See [example](https://github.com/netwerk-digitaal-erfgoed/project-organisations-datasets/tree/master/publication-model#example-serialization-in-json-ld)

### FURTHER REMARKS
* Versie beheer in github? Publicatie van dataset metadata op de front end?
* Bring it in line with the datasets on [labs](https://labs.beeldengeluid.nl/datasets)
* Uitzoeken of we bijvoorbeeld ook de [nsb propagandafilms ](https://www.beeldengeluid.nl/nieuws/beeld-en-geluid-stelt-propagandafilms-nsb-online-beschikbaar)beschikbaar hebben in de catalogus dataset. Deze staan in ieder geval op openbeelden. kunnen we ze dan bijvoorbeeld ook relateren aan de catalogus items. Bijv. https://www.openbeelden.nl/media/1129715/Mussert_spreekt_acte_1
NB Deze video is ook beschikbaar in GPP. In OpenBeelden staat verder geen reference naar de PID, of de URL van de GPP. 
* choose a publishing point... now, I share the data on my google drive. this should be another shared location. do we have a open data lab google drive? Or a place that is not attached to a person account? Like the webserver where we host the open data lab website? Or is that a github pages thingy?
### ACCEPTANCE CRITERIA
- ask Dimitra, ask Jesse, ask Jaap 
-

**Comment by wmelder** [comment]
also: choose a publishing point... now, I share the data on my google drive. this should be another shared location. do we have a open data lab google drive? Or a place that is not attached to a person account? Like the webserver where we host the open data lab website? Or is that a github pages thingy?

**Comment by wmelder** [comment]
I turns out that CC0 is not a llicense:
```It is also clear that CC0 is not a license, but a waiver.```
Don't know now what to do with this. Can not put it in the license field then.

**Comment by wmelder** [comment]
indeed this is how it was put in the doc:
https://creativecommons.org/publicdomain/zero/1.0/

**Comment by wmelder** [comment]
- the spreadsheet also contains organisation and datacatalog sheets
- the pygsheets library requires a user to handover his entire drive when he shares is... => find good alternative to get read access to one document only

**Comment by wmelder** [comment]
Trying the google API directly:
https://developers.google.com/sheets/api/guides/concepts

**Comment by wmelder** [comment]
Ok. it works fine to create a Google Cloud project and from there use the Google sheets API to read the spreadsheet.

Preparing to publish: 
- [ ] JSON-LD (serialized graph) 
- [ ] JSON (tree structured for front enders)

**Comment by wmelder** [comment]
Note that we might lock parts of the CSV to be sure content isn't changed unintentionally
