### ISSUE TITLE
EPIC B: As a heritage professional I want to have access to an up to date filtered set of openly accessible NISV catalogue metadata

### ISSUE THREAD

**Issue by 85jesse** [beeldengeluid/opendatalab#3]
As a heritage professional I want to have access to an up to date filtered set of openly accessible NISV catalogue metadata so I can reuse this data to enable search or built other views and applications on heritage information of combined collections.

**Acceptatie Criteria**
- [x] The dataset is published under an open license	(cc0)
- [x] The dataset is published in a standardised format (Schema.org)	
- [x] Every (audiovisual) resource in the dataset has a URI	
- [x] The dataset is up to date (max. 1 month) 
- [x] The dataset contains publicly accessible URIs to thesaurus terms (data.beeldengeluid.nl) so links can be made with external datasources
- [x] The dataset contains machine-readable license information (https://rightsstatements.org/en/)

**Comment by 85jesse** [comment]
Deze open data set wordt samengesteld op basis van de DAAN-metadata maar met de volgende aanpassingen:
- De dataset bevat uitsluitend velden die CC0 zijn 
- de data wordt geparsed naar standaarden als DublinCore en Schema.org
- interne thesaurus identifiers uit de DAAN-data worden gemapt naar gtaa-identifiers
- persistente links (URIs) worden toegevoegd

**Comment by wmelder** [comment]
```het IPR veld wordt geparsed naar machine-readable CC-URIs of rightlabels.org```
bedoel je https://rightsstatements.org/en/

**Comment by wmelder** [comment]
#1

**Comment by wmelder** [comment]
laatste loodjes

**Comment by wmelder** [comment]
deze tekst aan NOB gestuurd: 

hetgeen beloofd is is nu ook werkelijk klaar. 
Op deze URL vind je een SPARQL endpoint: https://cat.apis.beeldengeluid.nl/sparql

In de triple store achter dit SPARQL endpoint bevinden zich dus de triples van de catalogus die als CC0 data beschikbaar zijn. 

Als je de URL intikt in een browser krijg je een voorbeeld UI (Comunica web client). Mocht je vragen hebben over specifieke queries, dan hoor ik het graag. We kunnen ook desgewenst custom queries toevoegen.

Als je het endpoint benaderd vanuit een script kun je direct SPARQL queries versturen naar het endpoint. Doe dit een beetje slim ajb, door bijvoorbeeld LIMIT en OFFSET in je query te gebruiken.
